// Generated by CoffeeScript 1.3.3
var BubbleChart, root,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

BubbleChart = (function() {

  function BubbleChart(data) {
    this.hide_details = __bind(this.hide_details, this);

    this.show_details = __bind(this.show_details, this);

    this.hide_years = __bind(this.hide_years, this);

    this.display_years = __bind(this.display_years, this);

    this.move_towards_year = __bind(this.move_towards_year, this);

    this.display_by_year = __bind(this.display_by_year, this);

    this.move_towards_center = __bind(this.move_towards_center, this);

    this.display_group_all = __bind(this.display_group_all, this);

    this.start = __bind(this.start, this);

    this.create_vis = __bind(this.create_vis, this);

    this.create_nodes = __bind(this.create_nodes, this);

    var max_amount;
    this.data = data;
    this.width = 940;
    this.height = 900;
    this.tooltip = CustomTooltip("gates_tooltip", 240);
    this.center = {
      x: this.width / 2,
      y: this.height / 2
    };
    this.change_scale = d3.scale.linear().domain([-0.25, 0.25]).clamp(true).range([this.height / 9 * 6, this.height / 9 * 3]);
    this.center = {
      x: this.width / 2,
      y: this.height / 2
    };
    this.year_centers = {
      "2008": {
        x: this.width / 3,
        y: this.height / 2
      },
      "2009": {
        x: this.width / 2,
        y: this.height / 2
      },
      "2010": {
        x: 2 * this.width / 3,
        y: this.height / 2
      }
    };
    this.layout_gravity = -0.01;
    this.damper = 0.1;
    this.vis = null;
    this.nodes = [];
    this.force = null;
    this.circles = null;
    this.fill_color = d3.scale.quantile().domain([-0.25, -0.1, -0.02, 0.02, 0.1, 0.25]).range(['red', 'orange', 'gray', 'lightgreen', 'green']);
    max_amount = d3.max(this.data, function(d) {
      return parseInt(d.amount);
    });
    this.radius_scale = d3.scale.pow().exponent(0.5).domain([0, max_amount]).range([2, 85]);
    this.create_nodes();
    this.create_vis();
  }

  BubbleChart.prototype.create_nodes = function() {
    var _this = this;
    this.data.forEach(function(d) {
      var node;
      node = {
        id: d.code,
        radius: _this.radius_scale(parseInt(d.amount)),
        value: d.amount,
        name: d.name,
        org: d.depname,
        change: d.change,
        group: d.cat,
        year: 2013,
        x: Math.random() * 900,
        y: Math.random() * 800
      };
      return _this.nodes.push(node);
    });
    this.nodes.sort(function(a, b) {
      return b.value - a.value;
    });
    return this.nodes;
  };

  BubbleChart.prototype.create_vis = function() {
    var that,
      _this = this;
    this.vis = d3.select("#chart").append("svg").attr("width", this.width).attr("height", this.height).attr("id", "svg_vis");
    this.circles = this.vis.selectAll("circle").data(this.nodes, function(d) {
      return d.id;
    });
    that = this;
    this.circles.enter().append("circle").attr("r", 0).attr("fill", function(d) {
      return _this.fill_color(d.change);
    }).attr("stroke-width", 2).attr("stroke", function(d) {
      return d3.rgb(_this.fill_color(d.change)).darker();
    }).attr("id", function(d) {
      return "bubble_" + d.id;
    }).on("mouseover", function(d, i) {
      return that.show_details(d, i, this);
    }).on("mouseout", function(d, i) {
      return that.hide_details(d, i, this);
    });
    return this.circles.transition().duration(2000).attr("r", function(d) {
      return d.radius;
    });
  };

  BubbleChart.prototype.charge = function(d) {
    return -Math.pow(d.radius, 2.0) / 8;
  };

  BubbleChart.prototype.start = function() {
    return this.force = d3.layout.force().nodes(this.nodes).size([this.width, this.height]);
  };

  BubbleChart.prototype.display_group_all = function() {
    var _this = this;
    this.force.gravity(this.layout_gravity).charge(this.charge).friction(0.9).on("tick", function(e) {
      return _this.circles.each(_this.move_towards_center(e.alpha)).attr("cx", function(d) {
        return d.x;
      }).attr("cy", function(d) {
        return d.y;
      });
    });
    this.force.start();
    return this.hide_years();
  };

  BubbleChart.prototype.move_towards_center = function(alpha) {
    var _this = this;
    return function(d) {
      var cy, _ref;
      cy = (_ref = _this.change_scale(d.change)) != null ? _ref : _this.center.y;
      if (isNaN(cy)) {
        cy = _this.center.y;
      }
      d.x = d.x + (_this.center.x - d.x) * (_this.damper + 0.02) * alpha;
      return d.y = d.y + (cy - d.y) * (_this.damper + 0.02) * alpha;
    };
  };

  BubbleChart.prototype.display_by_year = function() {
    var _this = this;
    this.force.gravity(this.layout_gravity).charge(this.charge).friction(0.9).on("tick", function(e) {
      return _this.circles.each(_this.move_towards_year(e.alpha)).attr("cx", function(d) {
        return d.x;
      }).attr("cy", function(d) {
        return d.y;
      });
    });
    this.force.start();
    return this.display_years();
  };

  BubbleChart.prototype.move_towards_year = function(alpha) {
    var _this = this;
    return function(d) {
      var target;
      target = _this.year_centers[d.year];
      d.x = d.x + (target.x - d.x) * (_this.damper + 0.02) * alpha * 1.1;
      return d.y = d.y + (target.y - d.y) * (_this.damper + 0.02) * alpha * 1.1;
    };
  };

  BubbleChart.prototype.display_years = function() {
    var years, years_data, years_x,
      _this = this;
    years_x = {
      "2008": 160,
      "2009": this.width / 2,
      "2010": this.width - 160
    };
    years_data = d3.keys(years_x);
    years = this.vis.selectAll(".years").data(years_data);
    return years.enter().append("text").attr("class", "years").attr("x", function(d) {
      return years_x[d];
    }).attr("y", 40).attr("text-anchor", "middle").text(function(d) {
      return d;
    });
  };

  BubbleChart.prototype.hide_years = function() {
    var years;
    return years = this.vis.selectAll(".years").remove();
  };

  BubbleChart.prototype.show_details = function(data, i, element) {
    var content;
    d3.select(element).attr("stroke", "black");
    content = "<span class=\"name\">Title:</span><span class=\"value\"> " + data.name + " / " + data.id + " </span><br/>";
    content += "<span class=\"name\">Amount:</span><span class=\"value\"> $" + data.value + "</span><br/>";
    content += "<span class=\"name\">Dep:</span><span class=\"value\"> " + data.org + "</span>";
    content += "<span class=\"name\">change:</span><span class=\"change\"> " + (d3.format('+.2%')(data.change)) + "</span>";
    return this.tooltip.showTooltip(content, d3.event);
  };

  BubbleChart.prototype.hide_details = function(data, i, element) {
    var _this = this;
    d3.select(element).attr("stroke", function(d) {
      return d3.rgb(_this.fill_color(d.group)).darker();
    });
    return this.tooltip.hideTooltip();
  };

  return BubbleChart;

})();

root = typeof exports !== "undefined" && exports !== null ? exports : this;
